"""Self-contained HTML reports.

No CDN links, no build step: one file you can email, attach to a PR, or open
straight from disk. Bars are CSS widths rather than a charting library.
"""

from __future__ import annotations

import datetime as _dt
import html
import os
from collections.abc import Sequence

from ..eval.harness import EvalResult
from ..eval.sweep import SweepReport

_CSS = """
:root {
  --bg: #ffffff; --fg: #16181d; --muted: #6b7280; --line: #e5e7eb;
  --card: #f9fafb; --accent: #2563eb; --good: #059669; --mid: #d97706; --bad: #dc2626;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #0f1115; --fg: #e6e8ec; --muted: #9aa1ad; --line: #242832;
    --card: #161922; --accent: #60a5fa; --good: #34d399; --mid: #fbbf24; --bad: #f87171;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0; padding: 2.5rem 1.5rem; background: var(--bg); color: var(--fg);
  font: 15px/1.55 ui-sans-serif, -apple-system, "Segoe UI", Roboto, sans-serif;
}
.wrap { max-width: 1080px; margin: 0 auto; }
h1 { font-size: 1.6rem; margin: 0 0 .25rem; letter-spacing: -.01em; }
h2 { font-size: 1.1rem; margin: 2.5rem 0 .75rem; letter-spacing: -.01em; }
.sub { color: var(--muted); font-size: .9rem; margin-bottom: 2rem; }
.cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: .75rem; }
.card { background: var(--card); border: 1px solid var(--line); border-radius: 10px; padding: .9rem 1rem; }
.card .label { color: var(--muted); font-size: .75rem; text-transform: uppercase; letter-spacing: .05em; }
.card .value { font-size: 1.5rem; font-weight: 600; margin-top: .2rem; font-variant-numeric: tabular-nums; }
.scroll { overflow-x: auto; -webkit-overflow-scrolling: touch; }
table { border-collapse: collapse; width: 100%; min-width: 620px; font-size: .9rem; }
th, td { padding: .55rem .7rem; text-align: left; border-bottom: 1px solid var(--line); }
th { color: var(--muted); font-weight: 600; font-size: .75rem; text-transform: uppercase; letter-spacing: .04em; }
td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
tr.best td { background: color-mix(in srgb, var(--accent) 8%, transparent); font-weight: 600; }
tr.failed td { color: var(--bad); }
.bar { position: relative; display: block; height: 1.15rem; border-radius: 4px; background: var(--line); min-width: 90px; }
.bar > span { position: absolute; inset: 0 auto 0 0; border-radius: 4px; background: var(--accent); }
.bar > em { position: relative; font-style: normal; font-size: .78rem; padding-left: .4rem; line-height: 1.15rem; }
.good { color: var(--good); } .mid { color: var(--mid); } .bad { color: var(--bad); }
.miss { background: var(--card); border: 1px solid var(--line); border-left: 3px solid var(--bad);
        border-radius: 6px; padding: .6rem .85rem; margin-bottom: .5rem; }
.miss .q { font-weight: 600; }
.miss .e { color: var(--muted); font-size: .82rem; margin-top: .15rem; }
code { background: var(--card); border: 1px solid var(--line); border-radius: 4px; padding: .05rem .3rem; font-size: .85em; }
footer { margin-top: 3rem; color: var(--muted); font-size: .8rem; border-top: 1px solid var(--line); padding-top: 1rem; }
"""


def _esc(text) -> str:
    return html.escape(str(text), quote=True)


def _band(value: float) -> str:
    return "good" if value >= 0.8 else "mid" if value >= 0.5 else "bad"


def _bar(value: float, maximum: float = 1.0) -> str:
    pct = 0.0 if maximum <= 0 else max(0.0, min(1.0, value / maximum)) * 100.0
    return (
        f'<span class="bar"><span style="width:{pct:.1f}%"></span>'
        f'<em class="{_band(value)}">{value:.3f}</em></span>'
    )


def _card(label: str, value: str) -> str:
    return f'<div class="card"><div class="label">{_esc(label)}</div><div class="value">{_esc(value)}</div></div>'


def _document(title: str, body: str) -> str:
    stamp = _dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    return f"""<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{_esc(title)}</title>
<style>{_CSS}</style>
</head><body><div class="wrap">
{body}
<footer>Generated by <code>ragforge</code> on {stamp}</footer>
</div></body></html>"""


def render_eval_html(result: EvalResult, ks: Sequence[int] = (1, 3, 5, 10)) -> str:
    """Single-run report: headline metrics, the metric table, and the misses."""
    low, high = result.confidence_interval("recall@5")
    cards = "".join(
        [
            _card("recall@5", f"{result.metrics.get('recall@5', 0):.3f}"),
            _card("mrr", f"{result.metrics.get('mrr', 0):.3f}"),
            _card("ndcg@10", f"{result.metrics.get('ndcg@10', 0):.3f}"),
            _card("p95 latency", f"{result.latency_ms.get('p95', 0):.1f} ms"),
            _card("queries", str(result.n_queries)),
            _card("chunks", str(result.n_chunks)),
        ]
    )

    rows: list[str] = []
    for k in ks:
        if f"recall@{k}" not in result.metrics:
            continue
        get = result.metrics.get
        rows.append(
            "<tr>"
            f"<td class='num'>{k}</td>"
            f"<td>{_bar(get(f'recall@{k}', 0.0))}</td>"
            f"<td>{_bar(get(f'precision@{k}', 0.0))}</td>"
            f"<td>{_bar(get(f'hit@{k}', 0.0))}</td>"
            f"<td>{_bar(get(f'ndcg@{k}', 0.0))}</td>"
            "</tr>"
        )

    misses = result.failures("mrr", 0.0)
    misses_html = "".join(
        f'<div class="miss"><div class="q">{_esc(score.query)}</div>'
        f'<div class="e">expected: {_esc(", ".join(score.relevant[:4]))}</div></div>'
        for score in misses[:15]
    )
    if not misses:
        misses_html = "<p class='sub'>Every query retrieved at least one relevant document.</p>"

    body = f"""
<h1>{_esc(result.label)}</h1>
<div class="sub">Retrieval evaluation · recall@5 95% CI [{low:.3f}, {high:.3f}]</div>
<div class="cards">{cards}</div>

<h2>Metrics by cut-off</h2>
<div class="scroll"><table>
<thead><tr><th class="num">k</th><th>recall</th><th>precision</th><th>hit rate</th><th>nDCG</th></tr></thead>
<tbody>{''.join(rows)}</tbody>
</table></div>

<h2>Queries with no relevant result ({len(misses)})</h2>
{misses_html}
"""
    return _document(f"ragforge — {result.label}", body)


def render_sweep_html(report: SweepReport) -> str:
    """Leaderboard report comparing every configuration in a sweep."""
    ranked = report.ranked
    best = report.best
    healthy = [row for row in ranked if row.error is None]
    ceiling = max((row.get(report.primary) for row in healthy), default=1.0) or 1.0

    cards = "".join(
        [
            _card("configurations", str(len(ranked))),
            _card("queries", str(report.n_queries)),
            _card("best " + report.primary, f"{best.get(report.primary):.3f}" if best else "—"),
            _card(
                "spread",
                f"{(ceiling - min((r.get(report.primary) for r in healthy), default=0)):.3f}",
            ),
        ]
    )

    rows: list[str] = []
    for position, row in enumerate(ranked, start=1):
        if row.error:
            rows.append(
                f"<tr class='failed'><td class='num'>{position}</td><td>{_esc(row.label)}</td>"
                f"<td colspan='5'>{_esc(row.error)}</td></tr>"
            )
            continue
        css = " class='best'" if best and row.label == best.label else ""
        rows.append(
            f"<tr{css}>"
            f"<td class='num'>{position}</td>"
            f"<td>{_esc(row.label)}</td>"
            f"<td>{_bar(row.get(report.primary), ceiling)}</td>"
            f"<td class='num'>{row.get('mrr'):.3f}</td>"
            f"<td class='num'>{row.get('ndcg@10'):.3f}</td>"
            f"<td class='num'>{row.latency_ms.get('p95', 0):.1f}</td>"
            f"<td class='num'>{row.n_chunks}</td>"
            "</tr>"
        )

    body = f"""
<h1>Retrieval sweep</h1>
<div class="sub">{len(ranked)} configurations ranked by <code>{_esc(report.primary)}</code></div>
<div class="cards">{cards}</div>

<h2>Leaderboard</h2>
<div class="scroll"><table>
<thead><tr>
<th class="num">#</th><th>configuration</th><th>{_esc(report.primary)}</th>
<th class="num">mrr</th><th class="num">ndcg@10</th><th class="num">p95 ms</th><th class="num">chunks</th>
</tr></thead>
<tbody>{''.join(rows)}</tbody>
</table></div>
"""
    return _document("ragforge — sweep", body)


def write_report(content: str, path: str) -> str:
    directory = os.path.dirname(os.path.abspath(path))
    if directory:
        os.makedirs(directory, exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(content)
    return path


def write_eval_report(result: EvalResult, path: str, ks: Sequence[int] | None = None) -> str:
    return write_report(render_eval_html(result, ks or (1, 3, 5, 10)), path)


def write_sweep_report(report: SweepReport, path: str) -> str:
    return write_report(render_sweep_html(report), path)
